## -------------------------------------------------------------------------------------------------
##  SPY - C++ Informations Broker
##  Copyright: SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
## -------------------------------------------------------------------------------------------------
version: 1.0.{build}
os: Visual Studio 2019

environment:
  matrix:
  - ARCH: x86

build_script:
- mkdir build
- cd build
- cmake -G "Visual Studio 16 2019" -A x64 ..
- cmake --build . --target unit --verbose --config Release
- cmake --build . --target unit --verbose --config Debug

test_script:
- ctest -C Release -VV
- ctest -C Debug -VV
